### PR TITLE
Update ERD

### PR DESCRIPTION
**Pull request by KevinKelly25**
Added LastDDLOperation to the ERD htlm, png, and small png for issue #156

### CODE REVIEW

**Comment by KevinKelly25** [comment]
The updated PNGs look a more blurry then the originals. However, I am following the details left in PR #153. @smurthys other then exporting as png and having the border set to 10 was there any other options you had set? I am not sure what is causing the difference.

**Comment by smurthys** [comment]
I used "File/Export as/Advanced" in draw.io and only set the border size to 10.

While you are there, please switch the order of `LastDDLObject` and `LastDDLOperation`.

Thank you for taking care of this issue.

**Comment by KevinKelly25** [comment]
Fixed blurryness and switched order of LastDDLObject and LastDDLOperation.

For whatever reason. It seems if you have the same settings for File/Export as/png vs file/Export as/Advanced you will get different results, with the File/Export as/png coming out much more blurry.

**Comment by smurthys** [comment]
The changes look good. Thanks @KevinKelly25 for fixing this issue.

**Pull request merged**
