### PR TITLE
Add test Banner roster

### PR DESCRIPTION
**Pull request by smurthys**
The commits in this PR add a sample Banner CSV roster to facilitate testing of the eventual resolution to Issue #51 (add student users in bulk). A README file is also added.

The sample roster is added to the `tests` folder so it can become part of unit testing the code to add student users in bulk.

### CODE REVIEW

**Comment by afig** [comment]
Overall looks good. This will be definitely be helpful for eventually implementing a solution to above mentioned issue.

The only issue I noticed is that the filename on line 1 of the readme does not match the actual file name.

Another curiosity is that one of the rows contains an asterisk after each instance of "BS Computer Science". I am assuming it is intentional, and carries a meaning, but am not certain.

**Comment by srrollo** [comment]
I also think it looks good, besides the one filename/comment Andrew pointed out.

**Comment by smurthys** [comment]
Thanks for the review. I just pushed a commit renaming the file and correcting the error in the file prologue.

**Comment by smurthys** [comment]
@afig: The asterisk in the file is generated by Banner. The asterisk has meaning outside the context of ClassDB, but I left it in there so the data is representative.

**Comment by smurthys** [comment]
I will merge the changes tomorrow early morning EDT, just in case @s-aithal sees issues.

**Pull request merged**
