### PR TITLE
Add PNG version of ER Schema

### PR DESCRIPTION
**Pull request by smurthys**
I created a PNG version of the ERD. 

The image is full size and is useful for viewing on its own. I also have a 80% size version for embedding, but we should verify if we can already resize an image by percentage (not absolute size) when embedded in an MD file. (This PR is related to Issue #141.)

A quick web search revealed these potentially useful links. I don't know if there is more current information:
- https://github.com/blog/1395-relative-links-in-markup-files
- https://webapps.stackexchange.com/questions/29602/markdown-to-insert-and-display-an-image-on-github-repo#29631
- https://stackoverflow.com/questions/24383700/resize-image-in-the-wiki-of-github-using-markdown#24384029

### CODE REVIEW

**Comment by smurthys** [comment]
FYI, I used the Export function in draw.io. The key is to choose **border size of 10** instead of the default value of 0. I am documenting this information for when we need to recreate the image.

**Comment by smurthys** [comment]
I like to leave this PR open until we have figured out if a second smaller embed-friendly image is also required.

**Comment by srrollo** [comment]
I did a little playing around with image resizing, and I was unable to get and kind of % based resizing to work. It seems like only absolute resizing works on the wiki.

**Comment by smurthys** [comment]
Commit 80e78b2 adds ER-Schema-small.png which shows the schema at 80% size. At 70%, the image was too small to read, but we can change it when we review the final docs.

**Comment by smurthys** [comment]
Thanks @srrollo for verifying that sizes can't be specified in the Wiki.

**Pull request merged**
