### PR TITLE
Source directory reorganization

### PR DESCRIPTION
**Pull request by afig**
This PR separates all script files into one of three kinds: core, recommended, and optional (`core`, `reco`, and `opt` directories, respectively). Additionally, script files are now also separated into database scripts and server scripts (`db` and `server` directories under `src`, respectively).

Suffixes were added to file names corresponding to which of the three kinds they belong to.

For more information, see issue #142, which this PR fixes.

In terms of review, ensure that files are properly categorized. Particularly `addCatalogMgmtOpt.sql`, as I do not recall whether it was decided if it was recommended or optional.

Also, I left the uninstallation scripts (`removeFromDB.sql` and `removeFromServer.sql`) uncategorized (outside of a `core`, `reco`, or `opt` directory), as they remove all portions of the system.

I updated the file names inside of the `prepareDBCore.psql` script, added `addUserMgmtCore.sql` and `addClassDBRoleViewsCore.sql`, and removed `addConnectionMgmt.sql`.

### CODE REVIEW

**Comment by srrollo** [comment]
Looks good @afig. I think all the scripts have the correct placement. IMO, based on our discussion, `addCatalogMgmtOpt.sql` should be Opt.

The script names still need to be changed inside each file, but I imagine this is best left until we are sure of the location of each script. Also, should we include the 'full' path (ie. `db/core/addXYZCore.sql`), or just the filename in the prologue comments?

**Comment by afig** [comment]
Thanks for pointing out that the file names have to be updated for the headers, I had overlooked that when making these changes. However, I think it might over-complicate things if we add the full path.

I agree that the currently placement of `disableConnectionLoggingReco.psql` is rather confusing, but then again, it's not really an "uninstall" script either... 😕. I think it will be best to leave it for now and discuss it at some other point.

**Comment by smurthys** [comment]
Excellent work and analysis @afig and @srrollo.

I like the current location of the `remove*.sql` files. I recommend renaming them to `removeAllFrom*.sql` so it is obvious they will remove everything.

**Comment by smurthys** [comment]
I recommend renaming the `removeFrom*.sql` files as part of this PR to avoid issue-management effort. However, I am OK if the renaming is done after due to other considerations.

**Comment by afig** [comment]
The two files were renamed and headers updated:

`removeFromDB.sql` -> `removeAllFromDB.sql`

`removeFromServer.sql` -> `removeAllFromServer.sql`

**Comment by smurthys** [comment]
Nicely done. I'm eager to see how the new directory structure plays out.

**Pull request merged**
