### PR TITLE
Fix testUserMgmt.sql

### LINKED ISSUE #224: Test script testUserMgmt.sql is incomplete and runs unnecessary tests (ME)
The script `testUserMgmt.sql` has two problems:
- Does not test the key functionality in `addUserMgmtCore.sql`: rejecting inserts associated with non-ClassDB users, and rejecting all updates
- Unnecessarily tests row counts in activity tables, including initially testing if the activity tables are empty. Neither of the row-count tests are necessary.

### PR DESCRIPTION
**Pull request by smurthys**
The commits in this PR completely revise the test script `testUserMgmt.sql`. Fixes #224 

The revised script is tested against the dev branch. The script needs revision once PR #235 is merged. To be specific, two INSERT queries need to change to match the new schema of table `ConnectionActivity`.

In the meanwhile, I welcome comments on the changes.

### CODE REVIEW

**Comment by KevinKelly25** [comment]
It looks good so far and all test pass on 9.6 and 10.4. The only small thing I see wrong is the indentation on Ln 40.

**Comment by srrollo** [comment]
I think this looks good so far. Do we want to merge this now, or wait until #235 is merged and then update this branch again before merging? If we just want to merge, I would be OK with approving this now.

**Comment by smurthys** [comment]
I feel more comfortable merging after #235 is merged.

**Comment by afig** [comment]
Changes made to the tests look good. I agree that it would be a good idea to wait for PRs 235 and 237 to be merged before making the final changes related to those two PRs and merging this in.

**Comment by smurthys** [comment]
I just pushed some changes to the test script to account for v2.1 schema of tables `DDLActivity` and `ConnectionActivity`.

This PR is now ready for review.

**Pull request merged**
