### PR TITLE
Add Guard for DROP OWNED BY

### LINKED ISSUE #269: Guard uses of DROP OWNED: changed in pg9.5 (N)
The names CURRENT_USER and SESSION_USER in DROP OWNED is permitted only from pg9.5. Thus, this pattern of code needs to be guarded and executed as dynamic SQL in pg9.4 and earlier.

The script `testDisallowSchemaDrop.sql` has a few instances that need guarding.

### PR DESCRIPTION
**Pull request by KevinKelly25**
This PR adds a temporary function that when given a `DROP OWNED BY` query it will dynamically execute the query with an attached `CURRENT_USER`. All uses of `DROP OWNED BY CURRENT_USER` have been replaced with this temporary function with the replaced query as the parameter. This also maintains the purposefully odd case of `DrOP oWNeD BY ` on Ln120.

Fixes #269

### CODE REVIEW

**Comment by afig** [comment]
Changes look good and follow the recommend implementation. I only noticed some minor comment issues:

- L32: quieries -> queries

- L43: Add a separator (`----------------...`) here might not be necessary since it is not inside of the function and thus is already visually separated through indentation.

**Comment by smurthys** [comment]
Thanks @KevinKelly25. Just one minor improvement: change parameter name `query` to `queryHead` because its value is only the beginning of a query, rather than the entire query.

(I have yet to test the changes.)

**Comment by KevinKelly25** [comment]
@afig Thank you for the the suggestions. I think you and @smurthys posted around the same time and I missed your comment somehow. I apologize for that. I fixed this issues you mentioned.

**Comment by KevinKelly25** [comment]
Thank you for the reviews

**Pull request merged**
