### PR TITLE
Updated uninstall script for M2

### LINKED ISSUE #147: removeFromDB.sql relies on schema names matching user names (W)
`removeFromDB.sql` assumes that ClassDB user names match their schema names, and will always try and reassign the schema matching the user name instead of the user's actual schema. I believe getting the correct schema name with `ClassDB.getSchemaName()` should resolve this issue.

### PR DESCRIPTION
**Pull request by srrollo**
This PR updates the uninstall script to work with M2. I have changed to using the `DROP OWNED BY ClassDB` approach outlined [here](https://github.com/DASSL/ClassDB/issues/146#issuecomment-357379100). We can discuss if this solution is sufficient in our next sync, if necessary.

This method should no longer forcefully drop user objects that depend on ClassDB objects.

Fixes #147 and #146

### CODE REVIEW

**Comment by srrollo** [comment]
Closing until dir. reorg is done

**Comment by srrollo** [comment]
Reopened and editing PR comment

**Comment by srrollo** [comment]
I just pushed another commit that sets `ClassDB.IDNameDomain`'s owner to `ClassDB`, while before it was owned by the superuser. This is necessary for `DROP OWNED BY ClassDB` to work, since many of the ClassDB functions depend on `ClassDB.IDNameDomain`.

When testing the uninstaller, I would recommend creating a new install of ClassDB from the scripts in this branch, as many missing assigns and grants have been added in dev. I ran into several problems running the uninstaller that were due to old functions that have since been removed from ClassDB, or incorrect function permissions that are now fixed.

**Comment by smurthys** [comment]
Nice changes @srrollo. Using `DROP OWNED BY` is a good idea. (I should have suggested this approach earlier, because function `dropRole` already uses `DROP OWNED BY`.)

I have the following thoughts on `removeAllFromDB.sql`:
- The file prologue should probably say that the script stops if drop fails at any point (due to not using DROP...CASCADE)
- L101: The only reason to have this line is if the `ClassDB` schema is somehow not owned by the `ClassDB` role (and thus the schema is not already dropped by L98). Perhaps a comment to that effect helps.
- I recommend moving L98 and L101 to immediately after L 84.
- Doesn't the comment on L90 in general also apply to code in L87-L88?

Also, thank you for adding ownership to `ClassDB.IDNameDomain`. I'd missed doing that.

**Comment by smurthys** [comment]
FY, I'll be away for 60-90 minutes. So, please feel free to merge this PR unless one of you discovers something major. I'll approve the PR in anticipation of there being no such problem.

**Comment by afig** [comment]
Thanks for working on the uninstall script @srrollo. I tried running it on a clean M2 install, but received the following error (showing full output since it may be helpful in determining where the script fails):

```
classdbtest=# \i removeAllFromDB.sql
START TRANSACTION
SET
DO
DO
DO
DROP OWNED
DROP OWNED
DROP OWNED
DROP EVENT TRIGGER
DROP EVENT TRIGGER
DROP FUNCTION
DROP FUNCTION
DROP FUNCTION
DROP FUNCTION
psql:removeAllFRomDB.sql:98: ERROR:  cannot drop desired object(s) because other objects depend on them
DETAIL:  event trigger triggerddlcommandsqldrop depends on function classdb.logddlactivity()
```

Should `DROP EVENT TRIGGER IF EXISTS triggerDDLCommandSqlDrop;` be added to the uninstall? Likewise, should the accompanying `triggerDDLCommandEnd` also be added?

**Comment by srrollo** [comment]
Thanks for the review @smurthys. Thanks for pointing this out @afig. I had somehow pasted the wrong names for the event triggers in the `DROP EVENT TRIGGER` statements. The latest commit should fix this.

**Pull request merged**
